name: CI/CD for Django App

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test
  deploy:
    name: Deploy Django App to Server
    runs-on: ubuntu-latest
    needs: test

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} -p ${{ secrets.SSH_PORT }} '
            cd /home/ubuntu/restaurant-kitchen-service &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            sudo systemctl restart restaurant.service
          '
